### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by tangyi1989** [xwb1989/sqlparser#10]
Parse  sql "insert into trading.test(i, time) values(1, NOW())" will cause syntax error.

**Comment by matthewmueller** [comment]
Seems like `time` is causing the error, this works:

```sql
insert into trading.test(i, tim) values(1, NOW())
```

any thoughts on this one @xwb1989?

**Comment by xwb1989** [comment]
Apparently `time` is reserved as datatype keyword:

https://github.com/xwb1989/sqlparser/blob/master/token.go#L129
