### ISSUE TITLE
Syntax error on STRAIGHT_JOIN

### ISSUE THREAD

**Issue by donatj** [xwb1989/sqlparser#15]
Queries beginning with 'SELECT STRAIGHT_JOIN' fail with the message 'syntax error at position 21 near straight_join'

**Comment by bramp** [comment]
This issue seems fixed by d093d029e2170e41f99261ab9b8e947cf602a1d6 (Imported the latest https://github.com/youtube/vitess sqlparser)

**Comment by bramp** [comment]
Closing this issue. Feel free to reopen with an example if you still encounter the issue.
