### ISSUE TITLE
Missing Functions in WHERE clause

### ISSUE THREAD

**Issue by snadrus** [xwb1989/sqlparser#16]
Functions in SELECT operate correctly, but not in WHERE. I get a syntax error.

**Comment by bramp** [comment]
```go
Parse("SELECT a FROM t WHERE FUNC(a) = 1")
```

Seems to work fine. Would you provide an example of what doesn't work?

**Comment by bramp** [comment]
Closing this issue. Feel free to reopen with an example if you still encounter the issue.
