### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by detailyang** [xwb1989/sqlparser#2]
guys, i'm newbe to parser. how can i use sqlparser in my go project:)

**Comment by detailyang** [comment]
just to see the test, now i know how to use it:) thx

**Comment by xwb1989** [comment]
Thank you for the note anyways...I just updated the readme. Also please noticed that I change the repo name from "sql_parser" to "sqlparser"

**Comment by obonyojimmy** [comment]
hi how does one get the values of collumn like 'name' as  below :
`INSERT INTO QBAdminGroup.abmc_contacts('id', 'name') VALUES (1, 'jimmy')`

**Comment by xwb1989** [comment]
Hi @obonyojimmy , I just added a test to demonstrate how to retrieve those values. One caveat is this parser only accepts column names WITHOUT quotes. Here is the commit:

https://github.com/xwb1989/sqlparser/commit/a9cdf22bd561e715bba34ee228cb1c06bfa2719c

**Comment by haroroda** [comment]
Hi how can i parse a query and get every part of the query and its name?
i.e. query1:  INSERT INTO QBAdminGroup.abmc_contacts(id, name) VALUES (1, 'jimmy')
output1: 'DML', 'Keyword', 'Identifier', 'Keyword', 'Parenthesis'
query2: select 2 from admin
output2: 'DML', 'Integer', 'Keyword', 'Keyword'

the query part's name no need to be the same as the outputs,but i wonder if sqlparser has similar function or something else.Thanks!
