### ISSUE TITLE
Support for current_timestamp

### ISSUE THREAD

**Issue by yupengfei** [xwb1989/sqlparser#21]
I create a table with 

`UpdateDatetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',

it shows 

> syntax error at position 471 near 'current_timestamp'

**Comment by bramp** [comment]
Parsing of CREATE TABLE statements is not perfect. I've created a test case for this 3b9d32a5e86c7c2aef3d2f22b8dc3f1720e02c38 and will work upstream to get the parser improved.

**Comment by bramp** [comment]
I've fixed this [upstream](https://github.com/youtube/vitess/commit/5d7c5b2a2f6f1766843729a89b649e182441b529) and pull down the latest version. This should be fixed now.
