### ISSUE TITLE
`LOCK TABLES` and `UNLOCK TABLES` treated as syntax errors

### ISSUE THREAD

**Issue by dt** [xwb1989/sqlparser#32]
Discovered while looking at `mysqldump`'s default output, which contains a couple things that currently cause syntax errors. 

A `mysqldump` file consists of SQL statements that create tables and insert rows into them. By default it places `LOCK TABLES` and `UNLOCK TABLES` statements around its inserts, but currently these are not handled by the parser.

**Comment by sjezewski** [comment]
Similar issue ... trying to parse the output generated by a single table pgdump, the `COPY` statment is treated as a syntax error:

```
COPY public.company (id, name, age, address, salary) FROM stdin;
1	alice	100	1234 acme st                                      	1000000
2	bill	100	12345 acme st                                     	10000.0234
3	dakota	10	666 acme st                                       	100.023399
\.
```

Results in `syntax error at position 5 near 'COPY'`

**Comment by dt** [comment]
I added LOCK and UNLOCK to upstream vitess last month, so this can probably close since that'll filter down here when it rebases.

@sjezewski I doubt you'll have too much luck using this library to read pgdump output since it targets mysql dialect rather than postgres dialect SQL, and as you found, postgres-isms like COPY protocol will fail to parse. You might want to look for a postgres dialect parser?
