### ISSUE TITLE
Does it support "SELECT * FROM 11111.table1"  ?

### ISSUE THREAD

**Issue by liyinxin** [xwb1989/sqlparser#78]
Does it support "SELECT * FROM 11111.table1"  ?

I get this erorr:
SQL parsing error:syntax error at position 21 near '11111.'

**Comment by bramp** [comment]
I don't think that's a valid database/table identifier. Try wrapping it in backticks.

```
SELECT * FROM `11111`.table1
```

**Comment by liyinxin** [comment]
OK, I will try it

**Comment by liyinxin** [comment]
`SELECT * FROM `11111`.table1`

Thanks it works.

**Comment by samjewell** [comment]
Can you close this issue in that case? It's a bit distracting, when looking at the open issues on this repo

**Comment by bramp** [comment]
Working as intended
